version: '2'
services:
  kibana:
    build:
      context: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
  elasticsearch: # master
    build:
      context: es
    volumes:
      - ./data/es/master:/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  es_node:       # slave
    build:
      context: es
    volumes:
      - ./data/es/0:/elasticsearch/data
    ports:
      - 9200
      - 9300
    depends_on:
      - elasticsearch
  logstash:
    build:
      context: logstash
    ports:
      - "5530:5530/udp"
    volumes:
      - ./logstash/hsmp:/logstash/pipeline.conf
    links:
      - redis
      - elasticsearch
  pipe:
    build:
      context: pipe
    volumes:
      - ./pipe/pipe.py:/pipe/pipe.py
    environment:
      - ES_HOST=elasticsearch
      - REDIS_HOST=redis
    links:
      - redis
      - elasticsearch
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
