version: '2'
services:
  es0:
    container_name: elk_es0
    build:
      context: es
    volumes:
      - ./data/es/0:/elasticsearch/data
      - ./es/config/0/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9200:9200
      - 9300:9300
  es1:
    container_name: elk_es1
    build:
      context: es
    volumes:
      - ./data/es/1:/elasticsearch/data
      - ./es/config/1/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9201:9200
      - 9300
    depends_on:
      - es0
  es2:
    container_name: elk_es2
    build:
      context: es
    volumes:
      - ./data/es/2:/elasticsearch/data
      - ./es/config/2/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9202:9200
      - 9300
    depends_on:
      - es0

  syslogd_hsmp:
    container_name: elk_syslogd_hsmp
    build:
      context: syslogd
    command: syslogd.py -port 5530 -redis redis hsmp
    ports:
      - "5530:5530/udp"
    volumes:
      - ./syslogd/syslogd.py:/usr/bin/syslogd.py
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    links:
      - redis

  syslogd_vfw:
    container_name: elk_syslogd_vfw
    build:
      context: syslogd
    command: syslogd.py -port 5510 -redis redis vfw
    ports:
      - "5510:5510/udp"
    volumes:
      - ./syslogd/syslogd.py:/usr/bin/syslogd.py
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    links:
      - redis

  kibana:
    build:
      context: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    links:
      - es0

  pipe:
    build:
      context: pipe
    volumes:
      - ./pipe/pipe.py:/pipe/pipe.py
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - ES_HOST=es0
      - REDIS_HOST=redis
    links:
      - redis
      - es0
      - es1
      - es2
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
