#! /bin/bash


echo $PATH | egrep "${PWD}/bin"
if [ $? -ne 0 ]; then
    export PATH=$PATH:${PWD}/bin
fi

alias logs='docker-compose logs --tail=100 -f'

alias dc='docker-compose'
alias dcps='docker-compose ps'
alias dcup='docker-compose up -d'
alias dcdown='docker-compose down -v'

alias vfwl='docker-compose logs --tail=100 -f syslogd_vfw'
alias vfwr='docker-compose restart syslogd_vfw'
alias hsmpl='docker-compose logs --tail=100 -f syslogd_hsmp'
alias hsmpr='docker-compose restart syslogd_hsmp'
alias pipel='docker-compose logs --tail=100 -f pipe'
alias piper='docker-compose restart pipe'
